server:
  port: 8761

spring:
  application:
    name: jingf-eureka

eureka:
  instance:
    hostname: eureka.jingf.service
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false